### ISSUE TITLE
[Bug] Client crashes when opening an email on Android 6

### ISSUE THREAD

**Issue by ElongatedVeggie** [ProtonMail/proton-mail-android#164]
**Description**
A crash occurs when clicking on an email to read on Android 6. All other functionality seems to be fine.

**To Reproduce**
1. Press on an email
2. behold, the crash

**Expected behavior**
I expected it to not crash and read the email

**Logcat**

```
FATAL EXCEPTION: main
Process: ch.protonmail.android, PID: 13712
android.view.InflateException: Binary XML file line #116: Binary XML file line #38: Error inflating class ImageView
	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at i1.h.R(MessageDetailsAdapter.kt:4)
	at i1.h.onCreateViewHolder(MessageDetailsAdapter.kt:1)
	at androidx.recyclerview.widget.RecyclerView$g.createViewHolder(RecyclerView.java:2)
	at androidx.recyclerview.widget.RecyclerView$v.I(RecyclerView.java:34)
	at androidx.recyclerview.widget.RecyclerView$v.p(RecyclerView.java:1)
	at androidx.recyclerview.widget.RecyclerView$v.o(RecyclerView.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager$c.d(LinearLayoutManager.java:3)
	at androidx.recyclerview.widget.LinearLayoutManager.Q2(LinearLayoutManager.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager.q2(LinearLayoutManager.java:9)
	at androidx.recyclerview.widget.LinearLayoutManager.r1(LinearLayoutManager.java:64)
	at androidx.recyclerview.widget.RecyclerView.E(RecyclerView.java:8)
	at androidx.recyclerview.widget.RecyclerView.C(RecyclerView.java:9)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:2)
	at android.view.View.layout(View.java:16662)
	at android.view.ViewGroup.layout(ViewGroup.java:5439)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:12)
	at android.view.View.layout(View.java:16662)
	at android.view.ViewGroup.layout(ViewGroup.java:5439)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at androidx.core.widget.NestedScrollView.onLayout(NestedScrollView.java:1)
	at android.view.View.layout(View.java:16662)
	at android.view.ViewGroup.layout(ViewGroup.java:5439)
	at com.google.android.material.appbar.b.F(HeaderScrollingViewBehavior.java:22)
	at com.google.android.material.appbar.c.l(ViewOffsetBehavior.java:1)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:7)
	at android.view.View.layout(View.java:16662)
	at android.view.ViewGroup.layout(ViewGroup.java:5439)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:12)
	at android.view.View.layout(View.java:16662)
	at android.view.ViewGroup.layout(ViewGroup.java:5439)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16662)
	at android.view.ViewGroup.layout(ViewGroup.java:5439)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16662)
	at android.view.ViewGroup.layout(ViewGroup.java:5439)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16662)
	at android.view.ViewGroup.layout(ViewGroup.java:5439)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
	at android.view.View.layout(View.java:16662)
	at android.view.ViewGroup.layout(ViewGroup.java:5439)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2720)
	at android.view.View.layout(View.java:16662)
	at android.view.ViewGroup.layout(ViewGroup.java:5439)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2202)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1955)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1125)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6100)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858
```

**Smartphone:**
 - Device: LG G4
 - OS: Android 6
 - Version v3.0.0 (I assume it is the protonmail version)

**Additional context**
Happens with .apk used from releases of this repo and F-Droid (IzzyOnDroid repo)

**Comment by ElongatedVeggie** [comment]
Is fixed in v3.0.1. Thank you.
