### ISSUE TITLE
[Bug] Crash when clicking mailto link

### ISSUE THREAD

**Issue by thgoebel** [ProtonMail/proton-mail-android#47]
**Describe the bug**

When I clicked on a mailto link in an email, the app crashed.

**To Reproduce**

1. Open the email
2. Click on the link

Looking at the HTML body in the webclient reveals more about the culprit:
```
<a href="mailto:info@datasport.com?subject=Frage zur Rückerstattung" style="text-decoration: underline; color: #990000;" title="info@datasport.com">info@datasport.com</a>
```
If need be, I can privately forward the entire email.

**Log**

```
FATAL EXCEPTION: main
Process: ch.protonmail.android, PID: 4945
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.f0.d.q.f, parameter recipientList
	at ch.protonmail.android.utils.a0.a(Unknown Source:12)
	at ch.protonmail.android.views.PMWebViewClient.shouldOverrideUrlLoading(PMWebViewClient.java:7)
	at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:83)
	at XA.f(chromium-SystemWebView.apk-default-418310103:1)
	at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-SystemWebView.apk-default-418310103:16)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:326)
	at android.os.Looper.loop(Looper.java:160)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Expected behavior**

The composer should open.

**Screenshots**

💥

**Smartphone (please complete the following information):**
 - Device: OnePlus 5
 - OS: Android 9 / LineageOS 16
 - Version 1.13.16

**Comment by marinomeneghel** [comment]
Thanks for reporting this @thgoebel!

A solution have been implemented internally and will be rolled out with the next update. The code that fixes this will get to GitHub once the next release is out!
