### ISSUE TITLE
[Bug] App Crashes when writing new Mail or reply/forward

### ISSUE THREAD

**Issue by fuhrmeistery** [ProtonMail/proton-mail-android#74]
**Describe the bug**
App crashes when trying to create a new mail or reply/forward mails on Android 10

**To Reproduce**
1. Open App
2. Click on Pencil
3. App Crashes

**Expected behavior**
I would expect to be able to write mails using the app.

**Smartphone (please complete the following information):**
 - Device: OnePlus 7T
 - OS: Android 10/Oxygen OS
 - Version 1.13.25

**Additional context**
Viewing Mails works just fine

**Comment by marinomeneghel** [comment]
@fuhrmeistery thanks for reporting this. Was the app installed using GitHub's apk? 

If that's the case, could you try reinstalling it either though PlayStore or by re-downloading the GitHub build and chrck if the issue persists?

We've seen a similar issue happening on this version because of a corrupted build which was then removed.

**Comment by fuhrmeistery** [comment]
Switching to the play store worked for me.
Thank you for your work

**Comment by make-free-code** [comment]
@marinomeneghel I'm experiencing the same issue in `v1.13.25`. The APK was downloaded from GitHub. It crashes both when writing a new email and when replying to an email. It does not happen in `v1.13.24`. I'm seeing this in logcat:

```
03-07 19:40:48.598  9727  9727 W System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
03-07 19:40:48.598  9727  9727 W System.err: SLF4J: Defaulting to no-operation MDCAdapter implementation.
03-07 19:40:48.598  9727  9727 W System.err: SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
03-07 19:40:48.599  9727  9727 E AndroidRuntime: FATAL EXCEPTION: main
03-07 19:40:48.599  9727  9727 E AndroidRuntime: Process: ch.protonmail.android, PID: 9727
03-07 19:40:48.599  9727  9727 E AndroidRuntime: java.lang.AssertionError: java.lang.NoSuchFieldException: NONE
03-07 19:40:48.599  9727  9727 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:12)
03-07 19:40:48.599  9727  9727 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapters$30.create(TypeAdapters.java:5)
03-07 19:40:48.599  9727  9727 E AndroidRuntime: 	at com.google.gson.Gson.getAdapter(Gson.java:9)
03-07 19:40:48.599  9727  9727 E AndroidRuntime: 	at com.google.gson.Gson.toJson(Gson.java:11)
03-07 19:40:48.599  9727  9727 E AndroidRuntime: 	at com.google.gson.Gson.toJson(Gson.java:9)
03-07 19:40:48.599  9727  9727 E AndroidRuntime: 	at com.google.gson.Gson.toJson(Gson.java:4)
03-07 19:40:48.599  9727  9727 E AndroidRuntime: 	at com.google.gson.Gson.toJson(Gson.java:2)
03-07 19:40:48.599  9727  9727 E AndroidRuntime: 	at ch.protonmail.android.utils.o0.f.b(SerializationExtensions.kt:1)
03-07 19:40:48.599  9727  9727 E AndroidRuntime: 	at ch.protonmail.android.worker.drafts.CreateDraftWorker$a.a(CreateDraftWorker.kt:9)
03-07 19:40:48.599  9727  9727 E AndroidRuntime: 	at e.a.a.p.b.a.j(SaveDraft.kt:5)
03-07 19:40:48.599  9727  9727 E AndroidRuntime: 	at e.a.a.p.b.a$b.invokeSuspend(SaveDraft.kt:15)
03-07 19:40:48.599  9727  9727 E AndroidRuntime: 	at kotlin.e0.j.a.a.resumeWith(ContinuationImpl.kt:3)
03-07 19:40:48.599  9727  9727 E AndroidRuntime: 	at kotlinx.coroutines.w0.run(DispatchedTask.kt:19)
03-07 19:40:48.599  9727  9727 E AndroidRuntime: 	at kotlinx.coroutines.e3.a.V(CoroutineScheduler.kt:1)
03-07 19:40:48.599  9727  9727 E AndroidRuntime: 	at kotlinx.coroutines.e3.a$b.c(CoroutineScheduler.kt:4)
03-07 19:40:48.599  9727  9727 E AndroidRuntime: 	at kotlinx.coroutines.e3.a$b.m(CoroutineScheduler.kt:4)
03-07 19:40:48.599  9727  9727 E AndroidRuntime: 	at kotlinx.coroutines.e3.a$b.run(CoroutineScheduler.kt:1)
03-07 19:40:48.599  9727  9727 E AndroidRuntime: Caused by: java.lang.NoSuchFieldException: NONE
03-07 19:40:48.599  9727  9727 E AndroidRuntime: 	at java.lang.Class.getField(Class.java:1604)
03-07 19:40:48.599  9727  9727 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:6)
03-07 19:40:48.599  9727  9727 E AndroidRuntime: 	... 16 more
03-07 19:40:48.615  9727  9727 I Process : Sending signal. PID: 9727 SIG: 9
```

**Comment by marinomeneghel** [comment]
@make-free-code thanks for reporting this. As mentioned above, we saw this issue in relation to a corrupted build that was mistakenly published for a short time here on github. 

The corrupted build was replaced as soon as we learnt this. If the build you're experiencing the crash on wasn't installed recently you should be able to solve it by reinstalling from github or play store.

If the issue persists after reinstalling, please let us know and we'll have a look into it.

**Comment by make-free-code** [comment]
Thank you for your answer. I missed the point that a new build had been published for the same version. Thanks for clarifying. The freshly downloaded APK works fine. :raised_hands:
